### ISSUE TITLE
keenetic-pbr does not create ipset on startup

### ISSUE THREAD

**Issue by zibot** [maksimkurb/keen-pbr#1]
Привет!

Если интерфейс VPN создать не штатно в web-админке, а, например, с помощью [gost.run](https://gost.run/en), то из-за изоляции PBR работать не будет.
Нужно сделать no private-isolate или, что предподчтительней, добавить в iptables в таблицу filter правило типа такого:
```
CLIENT_SUBNET=192.168.1.0/24 # Клиентская подсеть, обычно на br0
VPN_IFACE=tun0 # VPN интефейс
iptables -w -A _NDM_SL_FORWARD -s $CLIENT_SUBNET -o $VPN_IFACE -j _NDM_SL_PRIVATE
```
Такое правило можно добавить в секцию [[ipset.iptables_rule]], но после этого перестает автоматически добавляться правило, которое маркирует трафик на/от хосты в ipset'е, поэтому маркирующее правило тоже надо добавлять в keenetic-pbr.conf.

И вот, собственно, проблема.
При старте маркирующее правило из keenetic-pbr.conf не добавляется, потому что, видимо, на этот момент не создан ipset.
Можно сделать в консоли /opt/etc/init.d/S80keenetic-pbr restart и заработает до перезагрузки.
Перезагрузку починил костылем, добавил в S80keenetic-bpr в начале функции apply_lists_and_routing() 
`ipset -q create bypass hash:ip`

**Comment by maksimkurb** [comment]
В конфиге `keenetic-pbr` можно создать несколько `iptables`-правил, например:

```toml
  [[ipset.iptables_rule]]
    chain = "PREROUTING"
    table = "mangle"
    rule = ["-m", "set", "--match-set", "{{ipset_name}}", "dst,src", "-j", "MARK", "--set-mark", "{{fwmark}}"]

  [[ipset.iptables_rule]]
    chain = "_NDM_SL_FORWARD"
    table = "filter"
    rule = ["-s", "192.168.1.0/24", "-o", "tun0", "-j", "_NDM_SL_PRIVATE"]
```

Вы пробовали такую конфигурацию?
