### ISSUE TITLE
Если нужно настроить принудительный вывод всего китайского IP-диапазона через интерфейс br0, как следует изменить или дополнить файл конфигурации?

### ISSUE THREAD

**Issue by DFR11** [maksimkurb/keen-pbr#7]
Если нужно настроить принудительный вывод всего китайского IP-диапазона через интерфейс br0, как следует изменить или дополнить файл конфигурации?

**Comment by maksimkurb** [comment]
Обсудили подробнее в Telegram: https://t.me/keen_pbr/1/1223

Пример конфига:
```toml
[general]
  # Directory for downloaded lists
  lists_output_dir = '/opt/etc/keen-pbr/lists.d'
  use_keenetic_dns = true
  fallback_dns = "1.1.1.1"

# Конфигурация для списка China (приоритет выше, идёт напрямую через ppp0)
[[ipset]]
  ipset_name = 'china_direct'
  lists = ['china']
  ip_version = 4
  flush_before_applying = true

  [ipset.routing]
    interfaces = ['ppp0']
    kill_switch = false
    fwmark = 1000
    table = 1000
    priority = 1000  # Более высокий приоритет (меньшее число)

# Конфигурация для VPN списка (идёт через VPN интерфейс nwg0)
[[ipset]]
  ipset_name = 'vpn'
  lists = ['vpn']
  ip_version = 4
  flush_before_applying = true

  [ipset.routing]
    interfaces = ['nwg0']
    kill_switch = true
    fwmark = 1010
    table = 1010
    priority = 1010  # Более низкий приоритет (большее число)

# IPv6 конфигурация для China
[[ipset]]
  ipset_name = 'china_direct_ipv6'
  lists = ['china']
  ip_version = 6
  flush_before_applying = true

  [ipset.routing]
    interfaces = ['ppp0']
    kill_switch = false
    fwmark = 1001
    table = 1001
    priority = 1001

# IPv6 конфигурация для VPN
[[ipset]]
  ipset_name = 'vpn_ipv6'
  lists = ['vpn']
  ip_version = 6
  flush_before_applying = true

  [ipset.routing]
    interfaces = ['nwg0']
    kill_switch = true
    fwmark = 1011
    table = 1011
    priority = 1011

# Список для VPN маршрутизации
[[list]]
  list_name = 'vpn'
  file = '/opt/etc/keen-pbr/vpn.lst'

# Список для прямой маршрутизации через China
[[list]]
  list_name = 'china'
  file = '/opt/etc/keen-pbr/china.lst'
```
